server:
  port: 8005

spring:
  application:
    name: chatbot-service
  
  datasource:
    url: jdbc:postgresql://postgres-vector:5432/chatbot_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

google:
  gemini:
    api-key: ${GOOGLE_GEMINI_API_KEY:}

services:
  user:
    url: http://user-service:8001
  product:
    url: http://product-service:8002
  order:
    url: http://order-service:8003

logging:
  level:
    com.microservices.chatbot: DEBUG
